language: python
python:
 - "3.4"
# command to install dependencies
install:
 - pip3 install pytest pytest-cov pytest-pep8
 - pip3 install python-coveralls
script:
 - py.test tests --doctest-modules --pep8 algs -v --cov algs --cov-report term-missing
after_success:
 - coveralls
